### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by caruso81** [Screenly/Screenly-Cast-for-WordPress#10]
I left this on WP also...sorry for the repetition.

I am getting the following error:

**Parse error**: syntax error, unexpected '[' in **/home/content/40/8060140/html/wordpress/wp-content/plugins/screenly-cast/inc/screenly-cast-settings.php** on line **45**

This loads in place of the site. Removing the plugin restores the site.

I've looked at the plugin, but I know zero about coding, so I can't really tell if something is wrong there or not.

(I'm on the latest WP...4.8)

**Comment by vpetersson** [comment]
@caruso81 What version of PHP are you using?

@petermonte could potentially be the trailing comma on [L48](https://github.com/Screenly/Screenly-Cast-for-WordPress/blob/master/screenly-cast/inc/screenly-cast-settings.php#L48)

**Comment by ggiessen** [comment]
older PHP versions don't like arrays like

[
   "foo" => "bar",
    "bar" => "foo",
]

replace it with this and it works fine:

array(
    "foo" => "bar",
    "bar" => "foo",
);

**Comment by vpetersson** [comment]
Good catch, @ggiessen. We're really not a PHP shop, so sorry for screwing that one up. ;)

@petermonte can you take a look at this today?

**Comment by petermonte** [comment]
Hi @ggiessen, thanks for the feedback. Next update will address this topic with grate concern.
@vpetersson will remove that trailing comma.
Thanks to both.

**Comment by caruso81** [comment]
So, I'm on 5.3, and I've replaced Lines 41-45....

[
            'label_for' => 'screenly_options_logo',
            'class' => 'screenly-row',
            'screenly_custom_data' => 'custom',
            [
        );
}

with...

array(
            'label_for' => 'screenly_options_logo',
            'class' => 'screenly-row',
            'screenly_custom_data' => 'custom',
            )
        );
}

And it seems to be working great.

Thanks to all for the help,
Wayne Crannell


⁣~~~~~~~~~~~~~~~~~~~~~~~
Dr. Wayne Crannell
Director of Choral & Vocal Music
Assoc Prof of Music
~~~~~~~~~~~~~~~~~~~~~~~
www.austincollege.edu/music

​

On Jun 28, 2017, 5:14 PM, at 5:14 PM, Viktor Petersson <notifications@github.com> wrote:
>@caruso81 What version of PHP are you using?
>
>@petermonte could potentially be the trailing comma on
>[L48](https://github.com/Screenly/Screenly-Cast-for-WordPress/blob/master/screenly-cast/inc/screenly-cast-settings.php#L48)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Screenly/Screenly-Cast-for-WordPress/issues/10#issuecomment-311807479

**Comment by vpetersson** [comment]
@caruso81 We've merged this upstream and released a new version. Please upgrade and let us know if that did the trick.

**Comment by vpetersson** [comment]
(Closing out this issue. Please comment if that didn't solve the issue.)

**Comment by caruso81** [comment]
Updated and works perfectly! Thanks.


⁣~~~~~~~~~~~~~~~~~~~~~~~
Dr. Wayne Crannell
Director of Choral & Vocal Music
Assoc Prof of Music
~~~~~~~~~~~~~~~~~~~~~~~
www.austincollege.edu/music

​

On Jul 2, 2017, 4:39 AM, at 4:39 AM, Viktor Petersson <notifications@github.com> wrote:
>(Closing out this issue. Please comment if that didn't solve the
>issue.)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Screenly/Screenly-Cast-for-WordPress/issues/10#issuecomment-312480882
