### ISSUE TITLE
Text scale template

### ISSUE THREAD

**Issue by vanrensav** [Screenly/Screenly-Cast-for-WordPress#9]
Hi im back again hehehe.

I found out that when displaying a page on screenly tv the text will show up way to small.
Can i fix this easy? i was thinking of editing your css file in screenly plugin folder but i will ask it first.

Thnx

**Comment by vpetersson** [comment]
I'm not sure that I follow. Can you provide:
 * A screenshot of the page
 * The URL you're using to access the page
 * What type of page it is (from WordPress' perspective)

**Comment by vpetersson** [comment]
Closing this out until we've been able to reproduce this.
